name: Urban Utopia 2024 (frontend)

on:
  push:
    branches:
      - main

jobs:

  build_and_push_frontend_image:
    name: Build frontend image and push to the DockerHub
    runs-on: ubuntu-latest
    steps:
      - name: Clone project to runner
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Push frontend image to the Dockerhub
        uses: docker/build-push-action@v4
        with:
          context: .
          push: True
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/urban_utopia_2024_frontend:latest

  deploy_on_server:
    name: Deploy project on server
    needs: build_and_push_frontend_image
    runs-on: ubuntu-latest
    steps:
      - name: Clone project to runner
        uses: actions/checkout@v3
      - name: Executing remote ssh commands to deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/urban_utopia_2024
            sudo docker compose down
            sudo docker image rm ${{ secrets.DOCKERHUB_USERNAME }}/urban_utopia_2024_frontend
            sudo docker image rm ${{ secrets.DOCKERHUB_USERNAME }}/urban_utopia_2024_gateway
            sudo docker volume rm urban_utopia_2024_urban_utopia_2024_static_volume
            sudo docker compose up -d --build
            sudo service nginx restart
  
  send_message_telegram:
    name: Send message to telegram
    needs: deploy_on_server
    runs-on: ubuntu-latest
    steps:
      - name: Send message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_ME_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: ✅ Деплой "Urban Utopia 2024 (frontend)" выполнен успешно!
